//
// Created by patri on 06-09-2026.
//
#ifndef TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_QUEUE_H
#define TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_QUEUE_H
class Queue {
    

};


#endif //TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_QUEUE_H
