//
// Created by patri on 19-09-2026.
//

#ifndef TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_STACK_H
#define TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_STACK_H


class Stack {
    
};


#endif //TALLER1EDATOS_PATRICIOVIDAL_VICENTEGARRIGA_STACK_H
